# See http://www.appveyor.com/docs/appveyor-yml for many more options

# Makes sure at least PS v5 is present
os: WMF 5

build: false

# Start deployment script
test_script:
  - ps: |
    Install-PackageProvider -Name 'Nuget' -ForceBootstrap
    Install-Module -Name 'InvokeBuild' -RequiredVersion 3.5.1
    Install-Module -Name 'PSDeploy' -RequiredVersion 0.1.27
    Invoke-Build -Task 'Deploy'