# See http://www.appveyor.com/docs/appveyor-yml for many more options

version: 1.0.{build}

# No need for us to increment on pull requests, just validate
pull_requests:
  do_not_increment_build_number: true

# We don't build tags
skip_tags: true

# Ensures that PS v5 will be present
image: WMF 5

# No need to publish artifacts either
nuget:
  disable_publish_on_pr: true

build: off

# Use this to install any prerequisites
test_script:
- ps: >-
    Install-PackageProvider -Name 'Nuget' -ForceBootstrap -Force

    Install-Module -Name 'InvokeBuild' -MinimumVersion 3.5.1 -Force

    Install-Module -Name 'MSOnline' -MinimumVersion 1.1.166.0 -Force

    Install-Module -Name 'PSDeploy' -MinimumVersion 0.1.27 -Force

    Install-Module -Name 'Pester' -MinimumVersion 4.0.2 -Force

    Invoke-Build -Task Deploy
